export default {
  login: 'nosregor',
  id: 7705200,
  node_id: 'MDQ6VXNlcjc3MDUyMDA=',
  avatar_url: 'https://avatars0.githubusercontent.com/u/7705200?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/nosregor',
  html_url: 'https://github.com/nosregor',
  followers_url: 'https://api.github.com/users/nosregor/followers',
  following_url: 'https://api.github.com/users/nosregor/following{/other_user}',
  gists_url: 'https://api.github.com/users/nosregor/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/nosregor/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/nosregor/subscriptions',
  organizations_url: 'https://api.github.com/users/nosregor/orgs',
  repos_url: 'https://api.github.com/users/nosregor/repos',
  events_url: 'https://api.github.com/users/nosregor/events{/privacy}',
  received_events_url: 'https://api.github.com/users/nosregor/received_events',
  type: 'User',
  site_admin: false,
  name: 'Andrew Rogerson',
  company: 'car2go GmbH',
  blog: 'http://andrewrogerson.xyz',
  location: 'Berlin, Germany',
  email: null,
  hireable: true,
  bio: null,
  public_repos: 93,
  public_gists: 7,
  followers: 17,
  following: 49,
  created_at: '2014-05-26T19:03:53Z',
  updated_at: '2020-01-21T20:48:01Z'
};
